[package]
name = "lib"
version = "1.3.0"
edition = "2021"
authors = ["Martin Berg Alstad"]

[lib]

[dependencies]
# Api
axum = { version = "0.7.5", optional = true, features = ["multipart"] }
tower = { version = "0.4.13", optional = true }
tower-http = { version = "0.5.2", optional = true, features = ["trace", "cors", "normalize-path"] }
# Async
tokio = { version = "1.38.0", optional = true, features = ["fs"] }
tokio-util = { version = "0.7.11", optional = true, features = ["io"] }
# Error handling
thiserror = { version = "1.0.61", optional = true }
# Logging
tracing = { version = "0.1.40", optional = true }
tracing-subscriber = { version = "0.3.18", optional = true }
# Parsing
nom = { version = "7.1.3", optional = true }
# Serialization / Deserialization
serde = { version = "1.0.203", optional = true, features = ["derive"] }
# Derive macros
derive = { path = "derive", optional = true }

[features]
axum = ["dep:axum", "dep:tower", "dep:tower-http", "dep:thiserror", "dep:tracing", "dep:tracing-subscriber"]
tokio = ["dep:tokio"]
io = ["dep:tokio", "dep:tokio-util"]
iter = []
nom = ["dep:nom"]
serde = ["dep:serde"]
derive = ["dep:derive", "axum", "serde"]
