[package]
name = "diesel-crud-derive"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
deluxe = { workspace = true }
proc-macro2 = { workspace = true }
