[package]
name = "openai-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../..", features = ["openai", "io"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
futures = "0.3.0"
async-openai = "0.23.0"
