[package]
name = "multipart_file"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../..", features = ["axum"] }
axum = "0.7.5"
tokio = { version = "1.40", features = ["rt-multi-thread", "macros"] }
